server:
  port: 8060

eureka:
  instance:
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://config-service:8888
  cloud:
    gateway:
      routes:
        - id: products-service
          uri: lb://products-service
          predicates:
            - Path=/api/v1/products/**
          filters:
            - AuthFilter
        - id: orders-service
          uri: lb://orders-service
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - AuthFilter
        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/api/v1/security/**

